module.exports = {
  MAX_REPLIES_PER_CAMPAIGN_PER_HOUR: 5,
  MIN_SECONDS_BETWEEN_REPLIES: 120,
  CONFIDENCE_THRESHOLD: 8,
  TYPING_DELAY_MS: 80,
  SCROLL_PAUSE_MS: 1500,
  AI_RESPONSE_TIMEOUT_MS: 60000,
};
